apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWwtcm9vdC1wYXNz # "mysql-root-pass" encoded in base64
  MYSQL_PASSWORD: bXlwYXNzd29yZA==

