{
 "title": "Kubernetes pod monitoring",
 "description": "Monitor a Kubernetes cluster using Prometheus TSDB.  Shows overall cluster CPU / Memory / Disk usage as well as individual pod statistics.\r\n\r\nModified version of dashboard #162 to work with Prometheus 2.1+. \r\n\r\nNote - Managed Kubernetes instances (such as Azure AKS) might not give you access to FS stats, as you can see in the screenshot. You should be able to see those stats otherwise.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"^$Namespace$\"}[5m] ) )",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_memory_usage_bytes{image!=\"\",namespace=~\"^$Namespace$\"}[5m] ) )",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Network i/o",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{name!=\"\",namespace=~\"^$Namespace$\"}[5m])))",
     "legendFormat": "{{ pod_name }}"
    },
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_transmit_bytes_total{name!=\"\",namespace=~\"^$Namespace$\"}[5m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}